#!/usr/bin/env php
<?php
/**
* @author Chris Hilsdon <chris@koolserve.uk>
*/

namespace Backupz;

umask(0000);
set_time_limit(0);
ini_set('memory_limit','64M');
date_default_timezone_set('Europe/London');

require_once __DIR__.'/vendor/autoload.php';

$app = new Application();
$app->initilize();

$application = $app['console'];
$application->add(new Console\Backup\Database($app));
$application->add(new Console\Backup\DatabaseList($app));
$application->add(new Console\Backup\Files($app));
$application->add(new Console\Backup\FilesList($app));
$application->add(new Console\Cache\Clear($app));
$application->add(new Console\Cron\Run($app));
$application->run();
