version: '2'

services:
    php:
        image: php:7.0-fpm-alpine
        volumes:
            - ./public/index.php:/var/www/html/public/index.php
            - ./app:/var/www/html/app
            - ./src:/var/www/html/src
            - ./vendor:/var/www/html/vendor
    nginx:
        image: nginx:alpine
        links:
            - "php:php"
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./.config/nginx.conf:/etc/nginx/nginx.conf
